name: graph2doc2vec_env
dependencies:
  - numpy
  - pandas
  - nltk
  - SciPy
  - networkx
  - pip:
      - "mowl-borg"
      - "matplotlib"
      - "networkx"
      - "biopython"
      - "seaborn"
      # - "pickle-mixin"